services:

  configserver:
    image: "sandeepgottipati/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    image: "sandeepgottipati/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
     file: common-config.yml
     service: microservice-configserver-config


  #loans configs
  loans:
    image: "sandeepgottipati/loans:v2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  #cards configs:-
  cards:
    image: "sandeepgottipati/cards:v2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


networks:
  eazybank:
    driver: "bridge"